"""tier3 voting foundation

Revision ID: 452e80ecab89
Revises: c17fc6096ae7
Create Date: 2026-09-28 20:22:14.000658
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '452e80ecab89'
down_revision: str | None = '20260927_0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voter_invitations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_voter_invitations_email', 'voter_invitations', ['event_id', 'email'], unique=False)
    op.create_index(op.f('ix_voter_invitations_expires_at'), 'voter_invitations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_voter_invitations_token_hash'), 'voter_invitations', ['token_hash'], unique=True)
    op.create_table('voting_windows',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.CheckConstraint('opens_at < closes_at', name='ck_voting_window_range'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('ballots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('voter_invitation_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_invitation_id'], ['voter_invitations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voter_invitation_id')
    )
    op.create_table('ballot_entries',
    sa.Column('ballot_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ballot_id'], ['ballots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ballot_id', 'project_id'),
    sa.UniqueConstraint('ballot_id', 'position'),
    sa.UniqueConstraint('ballot_id', 'project_id')
    )
    op.create_table('project_votes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ballot_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('cast_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ballot_id'], ['ballots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ballot_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_votes')
    op.drop_table('ballot_entries')
    op.drop_table('ballots')
    op.drop_table('voting_windows')
    op.drop_index(op.f('ix_voter_invitations_token_hash'), table_name='voter_invitations')
    op.drop_index(op.f('ix_voter_invitations_expires_at'), table_name='voter_invitations')
    op.drop_index('ix_voter_invitations_email', table_name='voter_invitations')
    op.drop_table('voter_invitations')
    # ### end Alembic commands ###

